### PR TITLE
Feat/switch to vuejs

### PR DESCRIPTION
**Pull request by lahcenrahlaoui**
# PR Details

## Types of changes

- [ ] Docs change / refactoring / dependency upgrade
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Review by abderrahmaneMustapha — CHANGES_REQUESTED** [review]
please use clear name s for the components , functions , variables and files 
examples for bad names :  style0, navbar0, myfunction0 , myfucntion1

**Review by abderrahmaneMustapha — CHANGES_REQUESTED** [review]
please try to keep the README.md file and the .github folder

**Comment by lahcenrahlaoui** [comment]
I m working on it , I'll try my best  to fix that 

Thanks for the reminder

**Review by abderrahmaneMustapha — APPROVED** [review]

**Comment by abderrahmaneMustapha** [comment]
😎😎😎

**Pull request merged**
